/**
 * A local PRNG implementation tailored to match the deterministic sequence
 * generated by seedrandom v3 (which defaulted to an ARC4 algorithm).
 * Kept to preserve bit-for-bit identical outcomes for legacy trials
 * without relying on a third-party dependency.
 */
class AleaPRNG {
  private i: number = 0;
  private j: number = 0;
  private S: number[] = [];

  constructor(seed: string) {
    let key: number[] = [];
    const mask = 255;
    const width = 256;

    let smear = 0;
    let j_idx = 0;
    while (j_idx < seed.length) {
      const keyJ = key[mask & j_idx];
      const smearVal = keyJ === undefined ? 0 : keyJ * 19;
      smear ^= smearVal;
      key[mask & j_idx] = mask & (smear + seed.charCodeAt(j_idx++));
    }
    if (!key.length) {
      key = [0];
    }

    const keylen = key.length;
    let t: number;
    let i = 0;
    let j = 0;

    while (i < width) {
      this.S[i] = i++;
    }
    for (i = 0; i < width; i++) {
      this.S[i] = this.S[j = mask & (j + key[i % keylen] + (t = this.S[i]))];
      this.S[j] = t;
    }

    let count = width;
    let r = 0;
    i = this.i;
    j = this.j;
    while (count--) {
      t = this.S[i = mask & (i + 1)];
      r = r * width + this.S[mask & ((this.S[i] = this.S[j = mask & (j + t)]) + (this.S[j] = t))];
    }
    this.i = i;
    this.j = j;
  }

  int32(): number {
    let count = 4;
    let t: number;
    let r = 0;
    let i = this.i;
    let j = this.j;
    const mask = 255;
    const width = 256;

    while (count--) {
      t = this.S[i = mask & (i + 1)];
      r = r * width + this.S[mask & ((this.S[i] = this.S[j = mask & (j + t)]) + (this.S[j] = t))];
    }
    this.i = i;
    this.j = j;
    return r | 0;
  }
}

export class AleaUtil {
  /**
   * Generates a 128-bit hex hash from a user-provided string seed.
   */
  static get128BitHash(seed: string | undefined): string {
    const s = seed || '';
    if (/^[0-9a-f]{32}$/i.test(s)) {
      return s.toLowerCase();
    }
    const rng = new AleaPRNG(s);
    const arr = new Uint32Array(4);
    for (let i = 0; i < 4; i++) {
      arr[i] = Math.abs(rng.int32());
    }
    return Array.from(arr, (n) => n.toString(16).padStart(8, '0')).join('');
  }
}
