const fs = require('fs');
const path = require('path');
const packageJson = require('./package.json');

const versionFilePath = path.join(__dirname, 'src', 'environments', 'version.ts');
const srcEnvironmentsDir = path.dirname(versionFilePath);

if (!fs.existsSync(srcEnvironmentsDir)) {
  fs.mkdirSync(srcEnvironmentsDir, { recursive: true });
}

const content = `// This file is auto-generated by generate-version.js
export const APP_VERSION = 'v${packageJson.version}';
`;

fs.writeFileSync(versionFilePath, content, 'utf8');
console.log(`Generated version file with version v${packageJson.version}`);
