import { Injectable } from '@angular/core';
import { RandomizationConfig } from '../../../models/randomization.model';
import { APP_VERSION } from '../../../../environments/version';

@Injectable({ providedIn: 'root' })
export class CodeGeneratorService {
  private hashCode(str: string | undefined): number {
    // Note: RandomizationService.generateSchema always sets a seed before this runs,
    // so this fallback path should not be reached in normal usage.
    if (!str) return Math.floor(Math.random() * 1000000);
    const s = String(str);
    let hash = 0;
    for (let i = 0; i < s.length; i++) {
      const char = s.charCodeAt(i);
      hash = ((hash << 5) - hash) + char;
      hash |= 0;
    }
    // Use unsigned right-shift to get a non-negative 32-bit integer, then mod into
    // R's set.seed() / Python's SeedSequence / SAS's call streaminit range (0..2^31-2).
    // Math.abs(-2147483648) === 2147483648, which exceeds the 31-bit limit; this
    // approach avoids that edge case entirely.
    return (hash >>> 0) % 2147483647;
  }

  generateR(config: RandomizationConfig): string {
    const generatedAt = new Date().toISOString();
    const sites = config.sites || [];
    const blockSizes = config.blockSizes || [];
    const arms = config.arms || [];
    const strata = config.strata || [];
    const caps = config.stratumCaps || [];

    // Create a named vector mapping "Level1_Level2" to cap
    const rCapsVector = caps.map(c => `"${c.levels.join('_')}" = ${c.cap}`).join(',\n  ');

    return `# Randomization Schema Generation in R
# Protocol: ${config.protocolId || 'Unknown'}
# Study: ${config.studyName || 'Unknown'}
# Generated by Clinical Randomization Generator
# App Version: ${APP_VERSION}
# Generated At: ${generatedAt}
# PRNG Algorithm: Mersenne-Twister

# Set seed for reproducibility
# Note: R uses a different PRNG than the web tool, so the exact sequence will differ,
# but the statistical properties and parameters remain the same.
set.seed(${this.hashCode(config.seed)})

# Parameters
sites <- c(${sites.map(s => '"' + s + '"').join(', ')})
block_sizes <- c(${blockSizes.join(', ')})

# Stratum Caps
stratum_caps <- c(
  ${rCapsVector}
)

# Treatment Arms
arms <- c(${arms.map(a => '"' + a.name + '"').join(', ')})
ratios <- c(${arms.map(a => a.ratio).join(', ')})
total_ratio <- sum(ratios)

# Block Math Failsafe
if (any(block_sizes %% total_ratio != 0)) {
  stop("Block sizes must be exact multiples of the total allocation ratio.")
}

# Strata
${strata.map(s => `${s.id}_levels <- c(${(s.levels || []).map(l => '"' + l + '"').join(', ')})`).join('\n')}

# Generate all strata combinations
# stringsAsFactors=FALSE is required: expand.grid() creates factor columns by default,
# which causes paste() to emit integer level codes (1, 2, ...) instead of the actual
# label strings, breaking the stratum_caps named-vector lookup below.
strata_grid <- expand.grid(
  ${[...strata.map(s => `${s.id} = ${s.id}_levels`), 'stringsAsFactors = FALSE'].join(',\n  ')}
)
# If no strata are defined, expand.grid() returns 0 rows. Insert one empty row so
# the generation loop executes once (treating the whole trial as a single stratum).
if (nrow(strata_grid) == 0) strata_grid <- data.frame(row.names = 1L)

# Function to generate a single block
generate_block <- function(block_size) {
  multiplier <- block_size / total_ratio
  block <- rep(arms, times = ratios * multiplier)
  sample(block) # Shuffle
}

# Generate Schema
schema_list <- list()
row_idx <- 1

for (site in sites) {
  site_subject_count <- 0
  # seq_len() is used instead of 1:nrow() to avoid the R gotcha where 1:0 produces
  # c(1, 0) instead of an empty sequence when there are no rows.
  for (i in seq_len(nrow(strata_grid))) {
    stratum <- strata_grid[i, , drop=FALSE]
    # In the unstratified case, expand.grid() produces a 1-row, 0-column data.frame.
    # Force a scalar empty key so the stratum_caps named-vector lookup remains length-1.
    if (ncol(stratum) == 0) {
      stratum_key <- ""
    } else {
      # unlist() is required to coerce the data.frame row to a plain character vector
      # before pasting; directly pasting a data.frame can give unexpected results.
      stratum_key <- paste(unlist(stratum), collapse="_")
      if (length(stratum_key) == 0) stratum_key <- ""
    }
    max_subjects_per_stratum <- if (length(stratum_caps) > 0) unname(stratum_caps[stratum_key]) else 0
    if (is.na(max_subjects_per_stratum)) max_subjects_per_stratum <- 0

    stratum_subject_count <- 0
    block_number <- 1

    while (stratum_subject_count < max_subjects_per_stratum) {
      # Pick random block size
      current_block_size <- sample(block_sizes, 1)

      # Generate block
      current_block <- generate_block(current_block_size)

      for (treatment in current_block) {
        site_subject_count <- site_subject_count + 1
        stratum_subject_count <- stratum_subject_count + 1

        # Format Subject ID (Simplified)
        subject_id <- sprintf("%s-%03d", site, site_subject_count)

        row <- data.frame(
          SubjectID = subject_id,
          Site = site,
          BlockNumber = block_number,
          BlockSize = current_block_size,
          Treatment = treatment
        )
        row <- cbind(row, stratum)

        schema_list[[row_idx]] <- row
        row_idx <- row_idx + 1

        if (stratum_subject_count >= max_subjects_per_stratum) break
      }
      if (stratum_subject_count >= max_subjects_per_stratum) break
      block_number <- block_number + 1
    }
  }
}

schema <- do.call(rbind, schema_list)

# Guard: when no subjects were generated (e.g. all caps are 0 or sites is empty),
# do.call(rbind, list()) returns NULL. Create an empty typed data.frame so that
# downstream code (print, write.csv) does not error.
if (is.null(schema) || nrow(schema) == 0) {
  base_schema <- data.frame(
    SubjectID = character(0),
    Site = character(0),
    BlockNumber = integer(0),
    BlockSize = integer(0),
    Treatment = character(0)
  )
  schema <- cbind(base_schema, strata_grid[0, , drop=FALSE])
}
print(head(schema))

if (nrow(schema) > 0) {
  cat("\\n--- QC Check: Overall Allocation ---\\n")
  print(table(schema$Treatment))

  cat("\\n--- QC Check: Site-Level Balance ---\\n")
  print(table(schema$Site, schema$Treatment))

  cat("\\n--- QC Check: Dynamic Block Utilization ---\\n")
  print(table(schema$BlockSize))
} else {
  cat("\\n--- QC Check ---\\n")
  cat("No rows generated; skipping QC tables.\\n")
}

# write.csv(schema, "randomization_schema.csv", row.names=FALSE)
`;
  }

  generatePython(config: RandomizationConfig): string {
    const generatedAt = new Date().toISOString();
    const sites = config.sites || [];
    const blockSizes = config.blockSizes || [];
    const arms = config.arms || [];
    const strata = config.strata || [];
    const caps = config.stratumCaps || [];

    // Create dictionary mapping tuple of levels to cap
    const pyCapsDict = caps.map(c => `    (${c.levels.map(l => `"${l}"`).join(', ')}): ${c.cap}`).join(',\n');

    return `# Randomization Schema Generation in Python
# Protocol: ${config.protocolId || 'Unknown'}
# Study: ${config.studyName || 'Unknown'}
# App Version: ${APP_VERSION}
# Generated At: ${generatedAt}
# PRNG Algorithm: PCG64

import numpy as np
import itertools
import pandas as pd

# Set seed for reproducibility
rng = np.random.default_rng(${this.hashCode(config.seed)})

# Parameters
sites = [${sites.map(s => '"' + s + '"').join(', ')}]
block_sizes = [${blockSizes.join(', ')}]

# Stratum Caps Mapping
stratum_caps = {
${pyCapsDict || '    (): 0'}
}

# Treatment Arms
arms = [${arms.map(a => `{"name": "${a.name}", "ratio": ${a.ratio}}`).join(', ')}]
total_ratio = sum(arm["ratio"] for arm in arms)

# Strata
strata_levels = [
    ${strata.map(s => `[${(s.levels || []).map(l => '"' + l + '"').join(', ')}]`).join(',\n    ')}
]
strata_names = [${strata.map(s => '"' + s.id + '"').join(', ')}]

# Generate all strata combinations
strata_combinations = list(itertools.product(*strata_levels))

# Block Math Failsafe
if any(bs % total_ratio != 0 for bs in block_sizes):
    raise ValueError("Block sizes must be exact multiples of the total allocation ratio.")

schema = []

for site in sites:
    site_subject_count = 0
    for combo in strata_combinations:
        stratum = dict(zip(strata_names, combo))

        # Determine cap for this specific stratum combination
        max_subjects_per_stratum = stratum_caps.get(combo, 0)

        stratum_subject_count = 0
        block_number = 1

        while stratum_subject_count < max_subjects_per_stratum:
            # Pick random block size
            current_block_size = rng.choice(block_sizes)

            # Generate block
            multiplier = current_block_size // total_ratio
            block = []
            for arm in arms:
                block.extend([arm["name"]] * int(arm["ratio"] * multiplier))

            rng.shuffle(block)

            for treatment in block:
                site_subject_count += 1
                stratum_subject_count += 1

                # Format Subject ID (Simplified)
                subject_id = f"{site}-{site_subject_count:03d}"

                schema.append({
                    "SubjectID": subject_id,
                    "Site": site,
                    "BlockNumber": block_number,
                    "BlockSize": current_block_size,
                    "Treatment": treatment,
                    **stratum
                })

                if stratum_subject_count >= max_subjects_per_stratum:
                    break

            block_number += 1

df = pd.DataFrame(schema)
print("\\n--- Generated Randomization Schema (First 5 Rows) ---")
print(df.head())

print("\\n--- QC Check: Overall Allocation ---")
print(df['Treatment'].value_counts())

print("\\n--- QC Check: Site-Level Balance ---")
print(pd.crosstab(df['Site'], df['Treatment']))

print("\\n--- QC Check: Dynamic Block Utilization ---")
print(df['BlockSize'].value_counts())
# df.to_csv("randomization_schema.csv", index=False)
`;
  }

  generateSas(config: RandomizationConfig): string {
    const generatedAt = new Date().toISOString();
    const sites = config.sites || [];
    const blockSizes = config.blockSizes || [];
    const arms = config.arms || [];
    const strata = config.strata || [];
    const caps = config.stratumCaps || [];
    const totalRatio = arms.reduce((sum, a) => sum + a.ratio, 0);

    let code = `/* Randomization Schema Generation in SAS */
/* Protocol: ${config.protocolId || 'Unknown'} */
/* Study: ${config.studyName || 'Unknown'} */
/* App Version: ${APP_VERSION} */
/* Generated At: ${generatedAt} */
/* PRNG Algorithm: Mersenne Twister */

%let seed = ${this.hashCode(config.seed)};
%let total_ratio = ${totalRatio};

/* User-defined Parameters */
%let arms = ${arms.map(a => `"${a.name}"`).join(' ')};
%let ratios = ${arms.map(a => a.ratio).join(' ')};
%let block_sizes = ${blockSizes.join(' ')};
%let sites = ${sites.map(s => `"${s}"`).join(' ')};

/* Block Math Failsafe */
data _null_;
  _n_blocks = countw("&block_sizes.", ' ', 'q');
  do _i = 1 to _n_blocks;
    _block_size = input(scan("&block_sizes.", _i, ' ', 'q'), best.);
    if mod(_block_size, &total_ratio.) ^= 0 then do;
      call symputx('BLOCK_MATH_ERROR', 1);
      put "ERROR: Block size " _block_size " is not an exact multiple of total allocation ratio " &total_ratio. ".";
    end;
  end;
run;

%macro check_block_math;
  %if &BLOCK_MATH_ERROR. = 1 %then %do;
    %abort cancel;
  %end;
%mend check_block_math;
%check_block_math;
`;

    if (strata.length > 0) {
      code += `%let strata_factors = ${strata.map(s => `"${s.id}"`).join(' ')};\n`;
      for (const s of strata) {
        code += `%let ${s.id}_levels = ${(s.levels || []).map(l => `"${l}"`).join(' ')};\n`;
      }
    }

    code += `
/* 1. Build the Design Matrix (Sites and Strata) */
data _sites;
  length Site $50;
  _n_sites = countw(&sites., ' ', 'q');
  do _i = 1 to _n_sites;
    Site = dequote(scan(&sites., _i, ' ', 'q'));
    output;
  end;
  drop _i _n_sites;
run;
`;

    const designVars = ['Site'];
    if (strata.length > 0) {
      for (let i = 0; i < strata.length; i++) {
        const s = strata[i];
        designVars.push(s.id);
        code += `
data _strata_${i+1};
  length ${s.id} $50;
  _n_levels = countw(&${s.id}_levels., ' ', 'q');
  do _i = 1 to _n_levels;
    ${s.id} = dequote(scan(&${s.id}_levels., _i, ' ', 'q'));
    output;
  end;
  drop _i _n_levels;
run;
`;
      }

    }

    // Create the cap mapping dataset
    code += `
/* Define Stratum Caps Map */
data _caps;
  length max_subjects_per_stratum 8`;
    if (strata.length > 0) {
      strata.forEach(s => {
        code += ` ${s.id} $50`;
      });
    }
    code += `;\n`;

    if (caps.length === 0) {
        // default empty output just to have the dataset structure
        code += `  max_subjects_per_stratum = 0; output;\n`;
    } else {
        caps.forEach(c => {
          if (strata.length > 0 && c.levels.length === strata.length) {
            strata.forEach((s, idx) => {
              code += `  ${s.id} = "${c.levels[idx]}";`;
            });
          }
          code += `  max_subjects_per_stratum = ${c.cap};\n  output;\n`;
        });
    }
    code += `run;\n`;

    if (strata.length > 0) {
      code += `
proc sql noprint;
  create table _design as
  select a.Site`;
      for (let i = 0; i < strata.length; i++) {
        const char = String.fromCharCode(98 + i); // 'b', 'c', etc.
        code += `, ${char}.${strata[i].id}`;
      }
      // Add the cap join logic
      code += `, caps.max_subjects_per_stratum
  from _sites a`;
      for (let i = 0; i < strata.length; i++) {
        const char = String.fromCharCode(98 + i);
        code += `
  cross join _strata_${i+1} ${char}`;
      }
      // Merge caps
      code += `
  left join _caps caps on 1=1`;
      for (let i = 0; i < strata.length; i++) {
        const char = String.fromCharCode(98 + i);
        code += ` and ${char}.${strata[i].id} = caps.${strata[i].id}`;
      }
      code += `;\nquit;\n`;
    } else {
      code += `
proc sql noprint;
  create table _design as
  select a.Site, caps.max_subjects_per_stratum
  from _sites a
  cross join _caps caps;
quit;
`;
    }

    code += `
/* 2. Generate Blocks and Assign Treatments */
data _blocks;
  set _design;
  if missing(max_subjects_per_stratum) then max_subjects_per_stratum = 0;
  call streaminit(&seed.);
  length Treatment $50;

  _total_ratio = &total_ratio.;
  _subj_count = 0;
  block_num = 1;

  do while (_subj_count < max_subjects_per_stratum);
    /* Dynamic Block Selection */
    _rand_val = rand('uniform');
`;

    for (let i = 0; i < blockSizes.length; i++) {
      if (i === 0 && blockSizes.length === 1) {
        code += `    block_size = ${blockSizes[i]};\n`;
      } else if (i === 0) {
        const p = (i + 1) / blockSizes.length;
        code += `    if _rand_val <= ${p.toFixed(5)} then block_size = ${blockSizes[i]};\n`;
      } else if (i === blockSizes.length - 1) {
        code += `    else block_size = ${blockSizes[i]};\n`;
      } else {
        const p = (i + 1) / blockSizes.length;
        code += `    else if _rand_val <= ${p.toFixed(5)} then block_size = ${blockSizes[i]};\n`;
      }
    }

    code += `
    _subj_count = _subj_count + block_size;
    _multiplier = block_size / _total_ratio;
    _n_arms = countw(&arms., ' ', 'q');

    /* Generate Treatments for the Block */
    do _a = 1 to _n_arms;
      Treatment = dequote(scan(&arms., _a, ' ', 'q'));
      _arm_ratio = input(scan(&ratios., _a, ' '), best.);

      do _t = 1 to round(_arm_ratio * _multiplier);
        _rand_sort = rand('uniform');
        output;
      end;
    end;
    block_num = block_num + 1;
  end;
run;
`;

    code += `
/* 3. Enforce Physical Sorting to Permute Blocks */
`;
    const byVars = designVars.join(' ');
    code += `proc sort data=_blocks;
  by ${byVars} block_num _rand_sort;
run;
`;

    const lastDesignVar = designVars[designVars.length - 1];

    code += `
/* 4. Final Data Deliverable & Cleanup */
data final_schema;
  set _blocks;
  by ${byVars};

  retain _site_subj_count 0;
  if first.Site then _site_subj_count = 0;

  retain _stratum_subj_count;
  if first.${lastDesignVar} then _stratum_subj_count = 1;
  else _stratum_subj_count = _stratum_subj_count + 1;

  if _stratum_subj_count <= max_subjects_per_stratum then do;
    _site_subj_count = _site_subj_count + 1;

    /* Format Subject ID */
    length SubjectID $50;
    SubjectID = cats(Site, "-", put(_site_subj_count, z3.));

    output;
  end;

  drop _:;
run;
`;

    code += `
/* 5. Quality Control (QC) Checks */
proc freq data=final_schema;
  title "Overall Treatment Balance";
  tables Treatment / nocum;
run;

proc freq data=final_schema;
  title "Site-Level Treatment Balance";
  tables Site * Treatment / nocol nopercent;
run;

proc freq data=final_schema;
  title "Block Size Distribution";
  tables block_size / nocum;
run;

title "Randomization Schema Preview";
proc print data=final_schema(obs=20);
run;
title;
`;

    return code.trim() + '\n';
  }
}
