name: Cleanup PR Preview

on:
  pull_request:
    types: [closed]
jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7c394e58
      with:
        egress-policy: block
        allowed-endpoints: |-
          github.com:443
          api.github.com:443
          objects.githubusercontent.com:443
          registry.npmjs.org:443
          registry.yarnpkg.com:443
          nodejs.org:443
    - name: Checkout repository
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

    - name: Install pnpm
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
      with:
        run_install: false

    - name: Set up Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
      with:
        node-version: '22'
        cache: 'pnpm'

    - name: Install Dependencies
      run: pnpm install --frozen-lockfile

    - name: Delete Cloudflare Workers Preview
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      run: |
        npx wrangler delete equipose-pr-${{ github.event.pull_request.number }}
    permissions:
      contents: read
